name: Download and Process Crypto Data

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 1 * * 1-5'  # Run at 1 AM on weekdays

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run Python script to download crypto data
        run: python __crypto_config.py
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add files/crypto/exchanges.json files/crypto/cryptocurency.json
          git status
          if [ -z "$(git diff --staged)" ]; then
            echo "No changes to commit"
          else
            git commit -m "Update crypto data"
            git push
          fi
