name: Test

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 5 * * 1-5' 

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Test
        run: python __test.py
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add files/user_agents.json
          git commit -m "Update crypto listed data"
          git push
