name: Update User Agents

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  update-user-agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: python update_script.py
